default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>
  #postgres://[USUÁRIO]:[SENHA]@[HOST]:5432/[NOME_DO_BANCO]

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "").gsub("capp_development", "capp_test") %>

production:
  <<: *default